Repository justincase-jp/AWS-CDK-Kotlin-DSL, pull requests merged in 2021-04, with the labels that each got.

#54 Migrate version checks from Bintray to Artifactory
  buildSrc/src/main/kotlin/PackageManager.kt
  buildSrc/src/main/kotlin/data/BintrayVersionJson.kt
Labels: size/S

#56 add publishSpecificVersion task to CircleCI
  .circleci/config.yml
  build.gradle.kts
Labels: size/M

#57 add publishing
  build.gradle.kts
  buildSrc/src/main/kotlin/BuildFileGenerator.kt
Labels: size/S

#58 fix typo
  build.gradle.kts
Labels: size/XS

#59 fix versions
  build.gradle.kts
Labels: size/XS

#60 fix wrong parameter
  build.gradle.kts
Labels: size/XS

#61 fix versions
  build.gradle.kts
Labels: size/XS
